public enum TeamNames {
    DUKE, UNC, KENTUCKY, NEBRASKA, KANSAS, UCLA, MICHIGAN_STATE, VILLANOVA, GONZAGA, FLORIDA_STATE, BAYLOR, LOUISVILLE, TEXAS, OHIO_STATE, SYRACUSE, MARYLAND, ARIZONA, WISCONSIN, IOWA, MICHIGAN, TEXAS_TECH, PURDUE, VIRGINIA, TENNESSEE, LSU, HOUSTON, WEST_VIRGINIA, CREIGHTON, OREGON, COLORADO, SAN_DIEGO_STATE, STANFORD,
    // Add more teams here
}